# Generated by Django 5.1.7 on 2025-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='updates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='contacts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
